@host = http://localhost:5000

### Register Request

POST {{host}}/api/users/register
Accept: application/json
Content-Type: application/json

{
  "username": "CarlVonBahnhoff",
  "email": "carl@bahnhoff.de",
  "password": "Testinek1234!"
}

### Login Request

POST {{host}}/api/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "Carl Von Bahnhoff",
  "password": "Test1234!"
}

###
