@host = https://localhost:5001

### Register Request

POST {{host}}/api/users/register
Accept: application/json
Content-Type: application/json

{
  "username": "CarlVonBahnhoff",
  "email": "carl@bahnhoff.de",
  "password": "Testinek1234!"
}

### Login Request

POST {{host}}/api/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "carl@bahnhoff.de",
  "password": "Testinek1234!"
}

### Get User by Id

GET {{host}}/api/users/48138495-bef4-4550-93ea-7ca00bd95fa4
Accept: application/json

###