name: CI

env:
    DOTNET_VERSION: '9.0.x'
  
on:
    push:
        branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Run Tests
        run: dotnet test --configuration Release
        
      - name: Publish
        run: dotnet publish src/ForestOfTasks.Api/ForestOfTasks.Api.csproj --configuration Release -o artifacts
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: artifacts/